venus: Added missing static function
* Fix the following error: implicit declaration of function 'venus_hfi_process_sys_watchdog_timeout' [-We
rror=implicit-function-declaration]

Change-Id: If5d4a66e951122a2e1ea010faf46748782e793a4